python framediff_segmentation.py ..\SampleVideos\more\khan1\khan1.mp4 ..\alignments\khan1.json ..\SampleVideos\more\khan1\khan1_framediff.txt ..\Mainpage\khan1
python framediff_segmentation.py ..\SampleVideos\more\khan2\khan2.mp4 ..\alignments\khan2.json ..\SampleVideos\more\khan2\khan2_framediff.txt ..\Mainpage\khan2
python framediff_segmentation.py ..\SampleVideos\more\armando1\armando1.mp4 ..\alignments\armando1.json ..\SampleVideos\more\armando1\armando1_framediff.txt ..\Mainpage\armando1
python framediff_segmentation.py ..\SampleVideos\more\armando2\armando2.mp4 ..\alignments\armando2.json ..\SampleVideos\more\armando2\armando2_framediff.txt ..\Mainpage\armando2
python framediff_segmentation.py ..\SampleVideos\more\udacity1\udacity1.mp4 ..\alignments\udacity1.json ..\SampleVideos\more\udacity1\udacity1_framediff.txt ..\Mainpage\udacity1
python framediff_segmentation.py ..\SampleVideos\more\udacity2\udacity2.mp4 ..\alignments\udacity2.json ..\SampleVideos\more\udacity2\udacity2_framediff.txt ..\Mainpage\udacity2
python framediff_segmentation.py ..\SampleVideos\more\mit1\mit1.mp4 ..\alignments\mit1.json ..\SampleVideos\more\mit1\mit1_framediff.txt ..\Mainpage\mit1
python framediff_segmentation.py ..\SampleVideos\more\mit2\mit2.mp4 ..\alignments\mit2.json ..\SampleVideos\more\mit2\mit2_framediff.txt ..\Mainpage\mit2
python framediff_segmentation.py ..\SampleVideos\more\hwt1\hwt1.mp4 ..\alignments\hwt1.json ..\SampleVideos\more\hwt1\hwt1_framediff.txt ..\Mainpage\hwt1
python framediff_segmentation.py ..\SampleVideos\more\hwt2\hwt2.mp4 ..\alignments\hwt2.json ..\SampleVideos\more\hwt2\hwt2_framediff.txt ..\Mainpage\hwt2
python framediff_segmentation.py ..\SampleVideos\more\tecmath1\tecmath1.mp4 ..\alignments\tecmath1.json ..\SampleVideos\more\tecmath1\tecmath1_framediff.txt ..\Mainpage\tecmath1
python framediff_segmentation.py ..\SampleVideos\more\tecmath2\tecmath2.mp4 ..\alignments\tecmath2.json ..\SampleVideos\more\tecmath2\tecmath2_framediff.txt ..\Mainpage\tecmath2