python dynamic_linebreak.py ../SampleVideos/more/trushit/trushit_removelogo_panorama/negate/panorama.png ../SampleVideos/more/trushit/trushit_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ 
python dynamic_linebreak.py ../SampleVideos/more/khan8/khan8_panorama/negate/panorama.png ../SampleVideos/more/khan8/khan8_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan8/khan8_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan3/khan3_panorama/negate/panorama.png ../SampleVideos/more/khan3/khan3_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan3/khan3_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan4/khan4_panorama/negate/panorama.png ../SampleVideos/more/khan4/khan4_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan4/khan4_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan5/khan5_panorama/negate/panorama.png ../SampleVideos/more/khan5/khan5_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan5/khan5_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan6/khan6_panorama/negate/panorama.png ../SampleVideos/more/khan6/khan6_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan6/khan6_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan7/khan7_panorama/negate/panorama.png ../SampleVideos/more/khan7/khan7_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan7/khan7_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan1/khan1_panorama/negate/panorama.png ../SampleVideos/more/khan1/khan1_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan1/khan1_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan9/khan9_panorama/negate/panorama.png ../SampleVideos/more/khan9/khan9_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan9/khan9_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/khan2/khan2_panorama/negate/panorama.png ../SampleVideos/more/khan2/khan2_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/khan2/khan2_panorama/negate/panorama.png
python dynamic_linebreak.py ../SampleVideos/more/bigbang/bigbang_khan_panorama/negate/panorama.png ../SampleVideos/more/bigbang/bigbang_khan_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/bigbang/bigbang_khan_panorama/negate/panorama.png
#python dynamic_linebreak.py ../SampleVideos/more/mit6041x_1/mit6041x_1_panorama/negate/panorama.png ../SampleVideos/more/mit6041x_1/mit6041x_1_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../SampleVideos/more/mit6041x_1/mit6041x_1_panorama/negate/panorama.png
