python subline_merge_subfigure.py ../SampleVideos/more/khan1/khan1_removelogo.avi ../SampleVideos/more/khan1/khan1_panorama/negate/panorama.png ../SampleVideos/more/khan1/khan1_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan1.json "3-D Divergence Theorem Intuition" "Khan Academy" ../SampleVideos/more/khan1/khan1_framepos.txt ../SampleVideos/more/khan1/khan1_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan2/khan2_removelogo.avi ../SampleVideos/more/khan2/khan2_panorama/negate/panorama.png ../SampleVideos/more/khan2/khan2_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan2.json "Green's Theorem Proof Part 1" "Khan Academy" ../SampleVideos/more/khan2/khan2_framepos.txt ../SampleVideos/more/khan2/khan2_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan3/khan3_removelogo.avi ../SampleVideos/more/khan3/khan3_panorama/negate/panorama.png ../SampleVideos/more/khan3/khan3_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan3.json "Indefinite integrals of x raised to a power" "Khan Academy" ../SampleVideos/more/khan3/khan3_framepos.txt ../SampleVideos/more/khan3/khan3_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan4/khan4_removelogo.avi ../SampleVideos/more/khan4/khan4_panorama/negate/panorama.png ../SampleVideos/more/khan4/khan4_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan4.json "Swapping the bounds for definite integral" "Khan Academy" ../SampleVideos/more/khan4/khan4_framepos.txt ../SampleVideos/more/khan4/khan4_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan5/khan5_removelogo.avi ../SampleVideos/more/khan5/khan5_panorama/negate/panorama.png ../SampleVideos/more/khan5/khan5_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan5.json "Fundamental theorem of calculus" "Khan Academy" ../SampleVideos/more/khan5/khan5_framepos.txt ../SampleVideos/more/khan5/khan5_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan6/khan6_removelogo.avi ../SampleVideos/more/khan6/khan6_panorama/negate/panorama.png ../SampleVideos/more/khan6/khan6_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan6.json "Both bounds being a function of x" "Khan Academy" ../SampleVideos/more/khan6/khan6_framepos.txt ../SampleVideos/more/khan6/khan6_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan7/khan7_removelogo.avi ../SampleVideos/more/khan7/khan7_panorama/negate/panorama.png ../SampleVideos/more/khan7/khan7_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan7.json "Basic trig and exponential antiderivatives" "Khan Academy" ../SampleVideos/more/khan7/khan7_framepos.txt ../SampleVideos/more/khan7/khan7_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan8/khan8_removelogo.avi ../SampleVideos/more/khan8/khan8_panorama/negate/panorama.png ../SampleVideos/more/khan8/khan8_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan8.json "Applying the fundamental theorem of calculus" "Khan Academy" ../SampleVideos/more/khan8/khan8_framepos.txt ../SampleVideos/more/khan8/khan8_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/khan9/khan9_removelogo.avi ../SampleVideos/more/khan9/khan9_panorama/negate/panorama.png ../SampleVideos/more/khan9/khan9_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/khan9_aligned.json "Antiderivative of hairier expression" "Khan Academy" ../SampleVideos/more/khan9/khan9_framepos.txt ../SampleVideos/more/khan9/khan9_cursorpos.txt
#python subline_merge_subfigure.py ../SampleVideos/more/bigbang/bigbang_khan_removelogo.avi ../SampleVideos/more/bigbang/bigbang_khan_panorama/negate/panorama.png ../SampleVideos/more/bigbang/bigbang_khan_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/bigbang.json "Big Bang Introduction " "Khan Academy"
python subline_merge_subfigure.py ../SampleVideos/more/video1/video1_removelogo.avi ../SampleVideos/more/video1/video1_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video1/video1_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video1.json "Proving Trigonometry Formulas from Euler's Formula" "Lee Stemkoski" ../SampleVideos/more/video1/video1_framepos.txt ../SampleVideos/more/video1/video1_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video2/video2_removelogo.avi ../SampleVideos/more/video2/video2_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video2/video2_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video2.json "Properties of Linearity" "Dave Academy" ../SampleVideos/more/video2/video2_framepos.txt ../SampleVideos/more/video2/video2_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video3/video3_removelogo.avi ../SampleVideos/more/video3/video3_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video3/video3_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video3.json "Moment method estimation" "Machine Intelligence Wiki" .../SampleVideos/more/video3/video3_framepos.txt ./SampleVideos/more/video3/video3_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video4/video4_removelogo.avi ../SampleVideos/more/video4/video4_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video4/video4_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video4.json "The Big Bang: The Shape of the Universe" "PhysicistMichael" ../SampleVideos/more/video4/video4_framepos.txt ../SampleVideos/more/video4/video4_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video5/video5_removelogo.avi ../SampleVideos/more/video5/video5_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video5/video5_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video5.json "Uniform Distribution" "Actuarial Path" ../SampleVideos/more/video5/video5_framepos.txt ../SampleVideos/more/video5/video5_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video6/video6_removelogo.avi ../SampleVideos/more/video6/video6_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video6/video6_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video6.json "CBSE- Class 10-IIT Foundation-Quadratic Equations Completing the square method" "Sanjay Raj Jain" ../SampleVideos/more/video6/video6_framepos.txt ../SampleVideos/more/video6/video6_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video7/video7_removelogo.avi ../SampleVideos/more/video7/video7_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video7/video7_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video7.json "2.2.2 - Set Operations" "AntOnMath" ../SampleVideos/more/video7/video7_framepos.txt ../SampleVideos/more/video7/video7_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/video8/video8_removelogo.avi ../SampleVideos/more/video8/video8_removelogo_panorama/negate/panorama.png ../SampleVideos/more/video8/video8_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/video8.json "Conditional Probability 1" "Kathy Arcangeli" ../SampleVideos/more/video8/video8_framepos.txt ../SampleVideos/more/video8/video8_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/trushit/trushit_removelogo.avi ../SampleVideos/more/trushit/trushit_removelogo_panorama/negate/panorama.png ../SampleVideos/more/trushit/trushit_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/trushit.json "Algebra: Quick way of simplification and expansion" "Trushit Vaishnav" ../SampleVideos/more/trushit/trushit_framepos.txt ../SampleVideos/more/trushit/trusit_cursorpos.txt
python subline_merge_subfigure.py ../SampleVideos/more/tecmath1/tecmath1.mp4 ../SampleVideos/more/tecmath1/tecmath1_removelogo_panorama/negate/panorama.png ../SampleVideos/more/tecmath1/tecmath1_removelogo_fgpixel_objs_noseg/cleanup/negate/consecutive/ ../alignments/tecmath1.json "Fractions addition and subtraction trick - do them the fast way" "tecmath" ../SampleVideos/more/tecmath1/tecmath1_framepos.txt ../SampleVideos/more/tecmath1/tecmath1_cursorpos.txt
