python fgpixelgrad_segmentation.py 100
python fgpixelgrad_segmentation.py 300
python fgpixelgrad_segmentation.py 400
python fgpixelgrad_segmentation.py 600
python fgpixelgrad_segmentation.py 700
python fgpixelgrad_segmentation.py 1000
python fgpixelgrad_segmentation.py 1500